### ISSUE TITLE
Error when executing ksrates test in nextflow

### ISSUE THREAD

**Issue by dawickell** [VIB-PSB/ksrates#38]
I am trying to get ksrates running on my laptop (Macbook M1 Pro running macOS Monterey) using nextflow. I am able to get nextflow to run successfully but when I try to run the test example I get the following error: 

```
$ nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/VIB-PSB/ksrates` [determined_bernard] DSL2 - revision: bfbb623720 [master]


K S R A T E S   -   N E X T F L O W   P I P E L I N E   (v1.1.1)
----------------------------------------------------------------

Configuration file:                    ./config_elaeis.txt
Logs folder:                           logs_3cf4463c
Preserve leftover files:               false

Command line:               nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
Launch directory:           /Users/wickell/ksrates
Work directory:             /Users/wickell/ksrates/work
ksrates directory:          /Users/wickell/.nextflow/assets/VIB-PSB/ksrates

Start time:                 2022-04-28T09:05:59.358787-04:00


No such variable: outCheckConfig

 -- Check script '/Users/wickell/.nextflow/assets/VIB-PSB/ksrates/main.nf' at line: 252 or see '.nextflow.log' file for more details
```
When I check the .nextflow.log file it doesn't tell me much more than the initial error message 
I have also tried running the next flow pipeline on our server (running Ubuntu 14.04.5) and get the same error.

Any idea what might be going wrong?

**Comment by Cecilia-Sensalari** [comment]
Hi dawickell,

Thanks for pointing this out! I managed to recreate the same error when using the latest version of Nextflow (22.04.0.5697). Can you try using an older Nextflow version (21.10.6.5660, the version we used to test the code)? In the meantime I will look into how to make the code work with the latest Nextflow version.

A quick way to use a specific version of Nextflow is by adding the `NXF_VER` environmental varibale (see Nextflow [docs](https://www.nextflow.io/docs/latest/getstarted.html#updates)):
```
 NXF_VER=21.10.6 nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
```
Best,
Cecilia

**Comment by Cecilia-Sensalari** [comment]
I'm glad it helped.
Did you install the dependencies and ksrates yourself or did you use docker?

**Comment by dawickell** [comment]
I attempted to install the dependencies manually on my laptop. That being said, I have been able to get the example working on our server using singularity. Thanks again for all your help!

**Comment by Cecilia-Sensalari** [comment]
Hi, I'll now close this issue, but feel free to add other posts or open a new issue if needed!
