### ISSUE TITLE
singularity

### ISSUE THREAD

**Issue by major-one** [VIB-PSB/ksrates#40]
Hello
 @Cecilia-Sensalari 
After I try to run, I get an error like this, can you help me?Thank you very much。
`N E X T F L O W ~ version 21.10.6
Launching VIB-PSB/ksrates [nauseous_torricelli] - revision: https://github.com/VIB-PSB/ksrates/commit/bfbb62372016a883876398790e0954973724b606 [master]

K S R A T E S - N E X T F L O W P I P E L I N E (v1.1.1)
Configuration file: ./config_elaeis.txt
Logs folder: logs_f55ff9e5
Preserve leftover files: false

Command line: nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt
Launch directory: /share/home/stu_wangtianyou/soft/ksrates/test
Work directory: /share/home/stu_wangtianyou/soft/ksrates/test/work
ksrates directory: /share/home/stu_wangtianyou/.nextflow/assets/VIB-PSB/ksrates

Start time: 2022-05-12T16:46:58.801640+08:00

[- ] process > checkConfig -
[- ] process > checkConfig -
[- ] process > setupAdjustment -
[- ] process > setParalogAnalysis -
[- ] process > setOrthologAnalysis -
[- ] process > estimatePeaks -
[- ] process > wgdParalogs -
[- ] process > wgdOrthologs -
[- ] process > plotOrthologDistrib -
[- ] process > doRateAdjustment -
[- ] process > paralogsAnalyses -
[- ] process > drawTree -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
Failed to pull singularity image
command: singularity pull --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
status : 1
message:
[- ] process > checkConfig -
[- ] process > setupAdjustment -
[- ] process > setParalogAnalysis -
[- ] process > setOrthologAnalysis -
[- ] process > estimatePeaks -
[- ] process > wgdParalogs -
[- ] process > wgdOrthologs -
[- ] process > plotOrthologDistrib -
[- ] process > doRateAdjustment -
[- ] process > paralogsAnalyses -
[- ] process > drawTree -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
Failed to pull singularity image
command: singularity pull --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
status : 1 message:
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 1: Bootstrap:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 2: From:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 4: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 5: AUTHOR: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 7: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 12: fg: no job control
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/requirements.txt: line 9: scikit-learn==0.24.2: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 1: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 2: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: syntax error near unexpected token (' /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: with open("README.md", 'r') as f:'
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 15: ksrates: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 16: wgd_ksrates: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: syntax error near unexpected token (' /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: Test pipeline CI'
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
[- ] process > checkConfig -
[- ] process > setupAdjustment -
[- ] process > setParalogAnalysis -
[- ] process > setOrthologAnalysis -
[- ] process > estimatePeaks -
[- ] process > wgdParalogs -
[- ] process > wgdOrthologs -
[- ] process > plotOrthologDistrib -
[- ] process > doRateAdjustment -
[- ] process > paralogsAnalyses -
[- ] process > drawTree -
Pulling Singularity image docker://vibpsb/ksrates:latest [cache /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity/vibpsb-ksrates-latest.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /share/home/stu_wangtianyou/soft/ksrates/test/work/singularity -- Use env variable NXF_SINGULARITY_CACHEDIR to specify a different location
Error executing process > 'checkConfig'

Caused by:
Failed to pull singularity image
command: singularity pull --name vibpsb-ksrates-latest.img.pulling.1652345220904 docker://vibpsb/ksrates:latest > /dev/null
status : 1
message:
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 1: Bootstrap:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 2: From:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 4: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 5: AUTHOR: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 7: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 12: fg: no job control
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/requirements.txt: line 9: scikit-learn==0.24.2: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 1: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 2: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: syntax error near unexpected token (' /share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: with open("README.md", 'r') as f:'
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 15: ksrates: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 16: wgd_ksrates: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: syntax error near unexpected token (' /share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: Test pipeline CI'
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 1: import: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 2: import: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 3: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 4: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: syntax error near unexpected token context_settings={'help_option_names':' /share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: @click.group(context_settings={'help_option_names': ['-h', '--help']})'
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 20: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 24: apt-get: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 29: apt-get: command not found
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
Directory '/install' is not installable. File 'setup.py' not found.

======================================================================================
The pipeline terminated during process 'checkConfig' with the following error message:

Failed to pull singularity image

More details may be found in the error report above and/or in[.nextflow.log]`

[Uploading .nextflow.log…]()

`NXF_VER=21.10.6 nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt` is my command line

**Comment by major-one** [comment]
Is the singularity provided by your project available? Do I need to download it myself？but I don't have administrator rights

**Comment by major-one** [comment]
`singularity pull --name vibpsb-ksrates-latest.img docker://vibpsb/ksrates:latest`  after running.
like this 
`/share/home/stu_wangtianyou/soft/ksrates/singularity: line 1: Bootstrap:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 2: From:: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 4: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 5: AUTHOR: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 7: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 8: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 12: fg: no job control
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/requirements.txt: line 9: scikit-learn==0.24.2: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 1: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 2: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: syntax error near unexpected token `('
/share/home/stu_wangtianyou/soft/ksrates/setup.py: line 4: `with open("README.md", 'r') as f:'
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 15: ksrates: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 16: wgd_ksrates: command not found
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: syntax error near unexpected token `('
/share/home/stu_wangtianyou/soft/ksrates/README.md: line 1: `[![Test pipeline CI](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml/badge.svg)](https://github.com/VIB-PSB/ksrates/actions/workflows/test_pipeline.yml)'
bash: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 1: import: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 2: import: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 3: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 4: from: command not found
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: syntax error near unexpected token `context_settings={'help_option_names':'
/share/home/stu_wangtianyou/soft/ksrates/ksrates_cli.py: line 6: `@click.group(context_settings={'help_option_names': ['-h', '--help']})'
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 20: fg: no job control
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 24: apt-get: command not found
/share/home/stu_wangtianyou/soft/ksrates/singularity: line 29: apt-get: command not found
ERROR: Directory '/install' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`
I think I should have submitted a stupid question, sorry.
I changed your Singularity to singularity, I thought it was usable.

**Comment by Cecilia-Sensalari** [comment]
The Singularity image is available on Docker Hub, and you don't need administration rights to download and use it. Normally the Nextflow pipeline downloads it while running ksrates the first time; you can else download (pull) the image yourself in advance and tell Nextflow to use it from the Nextflow configuration file (see docs).

Many of those error lines above seem to involve the `singularity` file in the ksrates directory, which is just a file to make the image (for which you do need `sudo` rights). You can ignore that file and use the image on Docker Hub.

**Comment by major-one** [comment]
Thank you so much for answering my stupid question, I'm going to try to download Docker and run it again.

Because it prompted me that the singularity command was not found, I saw a Singularity under your directory, I foolishly thought that this 'S' ingularity could be used after changing it to 's' ingularity, and then a series of errors appeared.

**Comment by Cecilia-Sensalari** [comment]
Hi, I will now close this issue. Feel free to post another one if something else comes up!
