### ISSUE TITLE
TypeError: cannot convert the series to <class 'float'>

### ISSUE THREAD

**Issue by Biscuite-wzy** [VIB-PSB/ksrates#42]
Hi,
I met an error when I run the step " ksrates orthologs-adjustment". I do not know how to resolve it, can you help me? I would appreciate it. Here I have replaced the species name with A, B,C,D,....in INFO.

```
INFO    - - - - - - - - - - - - - - - - - - - - - -
INFO    Rate-adjustment of ortholog Ks distributions
INFO    Wed Jun 22 23:03:01 2022
INFO    - - - - - - - - - - - - - - - - - - - - - -
INFO    Loading parameters and input files
INFO
INFO    Performing rate-adjustment of each divergent pair by using one or more outgroups:
INFO     - Adjusting the peak for [A] and [B] with outspecies [C]
INFO     - Adjusting the peak for [A] and [B] with outspecies [D]
INFO     - Adjusting the peak for [A] and [B] with outspecies [E]
INFO     - Adjusting the peak for [A] and [B] with outspecies [F]
INFO     - Adjusting the peak for [A] and [B] with outspecies [G]
INFO     - Adjusting the peak for [A] and [B] with outspecies [H]
INFO     - Adjusting the peak for [A] and [B] with outspecies [I]
Traceback (most recent call last):
  File "/home/zhaoxy/python3.8/ksrates/bin/ksrates", line 33, in <module>
    sys.exit(load_entry_point('ksrates', 'console_scripts', 'ksrates')())
  File "/home/zhaoxy/python3.8/ksrates/bin/ksrates/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/zhaoxy/python3.8/ksrates/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/zhaoxy/python3.8/ksrates/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zhaoxy/python3.8/ksrates/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zhaoxy/python3.8/ksrates/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/zhaoxy/biosoft/ksrates/ksrates_cli.py", line 136, in orthologs_adjustment
    correct(config_file, expert, trios)
  File "/home/zhaoxy/biosoft/ksrates/ksrates/correct.py", line 71, in correct
    rate_species, rate_species_sd, rate_sister, rate_sister_sd = fcCorrect.decompose_ortholog_ks(db, species_sister, species_out, sister_out, peak_stats)
  File "/home/zhaoxy/biosoft/ksrates/ksrates/fc_rrt_correction.py", line 45, in decompose_ortholog_ks
    rel_rate_species_sd = sqrt(pow(sd_sp_out, 2) + pow(sd_sp_sis, 2) + pow(sd_sis_out, 2)) / 2.0 # also called k_AO_sd
  File "/home/zhaoxy/python3.8/ksrates/lib/python3.8/site-packages/pandas/core/series.py", line 185, in wrapper
    raise TypeError(f"cannot convert the series to {converter}")
TypeError: cannot convert the series to <class 'float'>
```

**Comment by Cecilia-Sensalari** [comment]
Hi Biscuite-wzy,

Thanks for reporting this. The line that gives the error is trying to perform a calculation, but apparently it doesn't have the right data type for it (here is the [function](https://github.com/VIB-PSB/ksrates/blob/bfbb62372016a883876398790e0954973724b606/ksrates/fc_rrt_correction.py#L8), line 45).
It might be due to the fact that the file where the function is taking these numbers from is not structured like it should be. It is the ortholog peak database (where the estimated modes of the ortholog distributions are stored), so could you have a look in there if the columns are correctly structured? E.g. One is missing, one is duplicated or the values in them don't look correct (especially under `Mode_SD`). Here below I took the example from the [docs](https://ksrates.readthedocs.io/en/latest/input_output.html#other-output) to show how the database is supposed to look like:
![image](https://user-images.githubusercontent.com/57489957/175278193-433f4228-b9e3-45f4-b36a-c47f5cf7b2a7.png)

Best,
Cecilia

**Comment by Biscuite-wzy** [comment]
Hi,


I have had a look in there the columns are correctly structured, as follows. Here I have replaced the full name of the species with an x. But several values in Mode_SD are zero, does that cause this error ?



Best wishes


787117923
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VIB-PSB/ksrates"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月23日(星期四) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VIB-PSB/ksrates] TypeError: cannot convert the series to <class 'float'&gt; (Issue #42)





 
Hi Biscuite-wzy,
 
Thanks for reporting this. The line that gives the error is trying to perform a calculation, but apparently it doesn't have the right data type for it (here is the function, line 45).
 It might be due to the fact that the file where the function is taking these numbers from is not structured like it should be. It is the ortholog peak database (where the estimated modes of the ortholog distributions are stored), so could you have a look in there if the columns are correctly structured? E.g. One is missing, one is duplicated or the values in them don't look correct (especially under Mode_SD). Here below I took the example from the docs to show how the database is supposed to look like:
 
 
Best,
 Cecilia

**Comment by Cecilia-Sensalari** [comment]
Hi @Biscuite-wzy,

I'm afraid your post doesn't have the image attached! Could you reload it? Thanks.

Cecilia

**Comment by Biscuite-wzy** [comment]
Oh, sorry! It may not be able to attach the image, now I attach the text, as follows,

        Species1        Species2        Mode    Mode_SD
Cxxx ricxxxx_Sxxxx axxxx        Cxxx ricxxxx    Sxxxx axxxx     0.024708414872798404    0.004435378327805361
Dxxx rexxx_Fxxx qxxxx   Dxxx rexxx      Fxxx qxxxx      0.08082974559686885     0.004282444310959067
Txxx cvxxx_Sxxx sxxxx   Txxx cvxxx      Sxxx sxxxx      0.08317025440313108     0.0
Dxxx rexxx_Pxxx gxxxx   Dxxx rexxx      Pxxx gxxxx      0.08317025440313108     0.0

**Comment by Cecilia-Sensalari** [comment]
By looking at the layout of the text above it seems that only the headers (`Species1` etc...) are separated by a tab, while the other fields below (`Cxxx ricxxxx_Sxxxx` etc...) are separated by a space. However the code expects a tab! This way the function can't understand which numbers to parse for the calculation and it takes the whole line as a Series.

Would you check if the lines have a space as separator and, in case, would you replace each of them with a tab and try to run it again?

**Comment by Cecilia-Sensalari** [comment]
Hi, I'll close this issue due to inactivity. Should you encounter similar problems, we'll reopen it!

Cecilia

**Comment by Biscuite-wzy** [comment]
Hi,
Thanks for your reply! I have found out the cause of this error, which was caused by an incorrect species name in the configure file.



787117923
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VIB-PSB/ksrates"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月12日(星期二) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VIB-PSB/ksrates] TypeError: cannot convert the series to <class 'float'&gt; (Issue #42)





 
Hi @Biscuite-wzy,
 
Have you had the chance to check the spacing in the table?
 I don't think that 0.0 values would be a problem.
 
Cheers,
 Cecilia

**Comment by Cecilia-Sensalari** [comment]
I see, thanks for letting us know :)
Best,
Cecilia

**Comment by Cecilia-Sensalari** [comment]
Hmm, this might actually be something to be caught in an error message, instead of letting it crash that way! Would you let me know which kind of incorrect name you were using?
