### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sjfleck** [VIB-PSB/ksrates#44]
Hello, I was able to install and use Singularity, but I'm having an issue with Nextflow. When I use "java -version" is get:
openjdk version "19.0.1" 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)

but when I use "wget -qO- https://get.nextflow.io | bash", I get this error:

NOTE: Nextflow is not tested with Java 1.8.0_331 -- It's recommended the use of version 11 up to 18

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/jgit/api/errors/GitAPIException has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
...

I'm not sure why the Nextflow installation is using the wrong version of java and I'm having trouble finding how to solve this online. I know this is only tangentially related to ksrates, but I would appreciate any help you can provide.

**Comment by sjfleck** [comment]
I was able to figure it out. I used brew to install openjdk version 17 and added this java to my path:
sudo ln -sfn /usr/local/opt/openjdk@17/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-17.jdk
echo 'export PATH="/usr/local/opt/openjdk@17/bin:$PATH"' >> ~/.zshrc
echo 'export CPPFLAGS="-I/usr/local/opt/openjdk@17/include"' >> ~/.zshrc

**Comment by Cecilia-Sensalari** [comment]
Hi, thanks for sharing your solution!
Cecilia
