### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by majssssa** [VIB-PSB/ksrates#55]
I ran into this problem when running nextflow run VIB-PSB/ksrates -- config. /config_elaeis.txt, how to solve this problem.
Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/VIB-PSB/ksrates/contents/nextflow.config

**Comment by Cecilia-Sensalari** [comment]
Hi majssssa,

Thanks for reaching out :) As far as I know, the missing manifest is not a problem.
If that above is exactly your command line, I noticed that there is an extra space between "--" and "config", and that the "." should be just before the "/". Would you try to see whether the following command line works? It's copy-pasted from the [docs](https://ksrates.readthedocs.io/en/latest/installation.html#testing-your-installation).
`nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt`

Cheers,
Cecilia

**Comment by majssssa** [comment]
Hi Cecilia,

I use the command line "nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt", and it didn't work. But the error informaiton is "https://github.com/VIB-PSB/ksrates.git: connection failed",  so I think the peoblem not command line but network.


Cheer,
majssssa``

**Comment by Cecilia-Sensalari** [comment]
Hi,

Not sure how to interpret that at the moment!
If you're on Linux, perhaps running 'nslookup github.com' can help clarifying? Should I have other ideas, I'll let you know.

Best,
Cecilia

**Comment by majssssa** [comment]
Hi,

I tried to change the computer and the network problem was solved successfully. But when i run again "nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt", I get the following error message.

N E X T F L O W  ~  version 23.10.1
Pulling VIB-PSB/ksrates ...
WARN: Cannot read project manifest -- Cause: connect timed out
Cannot find `VIB-PSB/ksrates` -- Make sure exists a GitHub repository at this address `https://github.com/VIB-PSB/ksrate

**Comment by majssssa** [comment]
Hi,

I tried to change the computer and the network problem was solved successfully. But when i run again "nextflow run VIB-PSB/ksrates --config ./config_elaeis.txt", I get the following error message.

N E X T F L O W ~ version 23.10.1
Pulling VIB-PSB/ksrates ...
WARN: Cannot read project manifest -- Cause: connect timed out
Cannot find VIB-PSB/ksrates -- Make sure exists a GitHub repository at this address `https://github.com/VIB-PSB/ksrate

Best,
majsssa

**Comment by Cecilia-Sensalari** [comment]
Hi :)

I gave it a try myself, and I think the error is triggered when using recent Nextflow versions, such as 23.10.1. Would it be possible for you to launch it with a version (up to) 22.10.0?
After 22.10.x, Nextflow implemented another syntax, and ksrates' code in the master branch is no yet compatible. There is an ongoing [PR](https://github.com/VIB-PSB/ksrates/pull/51) where I converted the code to the new syntax, but it has only been tested on the small `test` dataset.
If you can't (or don't want to) use an older Nextflow version, you could switch to the `nf_dsl2` [branch](https://github.com/VIB-PSB/ksrates/tree/nf_dsl2).
Keep me posted!

Kind regards,
Cecilia

**Comment by majssssa** [comment]
Hi :)

After running nextflow run VIB-PSB/ksrates --config./config_elaeis.txt, I started the normal analysis process, but there was an error in the 'wgdParalogs' process.An error message is displayed More details may be found in the error report above, in ./.nextflow.log, and/or following log file: rate_adjustment/elaeis/logs_103b80af/wgd_paralogs.log. The following is the contents of the file wgd_paralogs.log.

NF internal work directory for [setParalogAnalysis] process:
/media/desk15/sxq020/MJP/WGD_08_29/test_data/ksrates/example/work/aa/cc0b0af5a27233ad7cc74d7a2a56c6

[elaeis] Paralog TSV file not found [elaeis.ks.tsv]
[elaeis] Whole-paranome wgd pipeline will be started

[elaeis] Anchor pairs TSV file not found [elaeis.ks_anchors.tsv]
[elaeis] Collinearity wgd pipeline will be started

----------------------------------------------------------------

NF internal work directory for [wgdParalogs (1)] process:
/media/desk15/sxq020/MJP/WGD_08_29/test_data/ksrates/example/work/2a/0bcf0ea057370aeccbd5c580a5d55c

Using 1 thread(s)

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
Traceback (most recent call last):
  File "/usr/local/bin/ksrates", line 8, in <module>
    sys.exit(cli())
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ksrates_cli.py", line 58, in paralogs_ks
    from ksrates.wgd_paralogs import wgd_paralogs
  File "/usr/local/lib/python3.8/dist-packages/ksrates/wgd_paralogs.py", line 7, in <module>
    import ksrates.fc_wgd as fc_wgd
  File "/usr/local/lib/python3.8/dist-packages/ksrates/fc_wgd.py", line 10, in <module>
    from wgd_ksrates.ks_distribution import ks_analysis_paranome, ks_analysis_one_vs_one
  File "/usr/local/lib/python3.8/dist-packages/wgd_ksrates/ks_distribution.py", line 35, in <module>
    from .phy import run_phyml, phylogenetic_tree_to_cluster_format, run_fasttree
  File "/usr/local/lib/python3.8/dist-packages/wgd_ksrates/phy.py", line 35, in <module>
    import fastcluster
  File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/fastcluster.py", line 37, in <module>
    from _fastcluster import linkage_wrap, linkage_vector_wrap
ImportError: numpy.core.multiarray failed to import

**Comment by Cecilia-Sensalari** [comment]
Hi!

Based on the error message`RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe`, it should be related to the numpy version. Can it be that you're using a different one (more recent?) than what ksrates was made with? The [requirements file](https://github.com/VIB-PSB/ksrates/blob/master/requirements.txt) sets up `numpy==1.21.2`.
Can you check which version you are using, and try with 1.21.2 or some other one not too distant from it?

PS. It seems that you managed to fix the original problem at the beginning of this issue; feel free to close any issue that you think it's completed and to open a new one to start over a different topic!

**Comment by majssssa** [comment]
Hi!

I ran "pip show numpy" to check the version of numpy I installed and the output is as follows.
Version: 1.21.2
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: /media/desk15/sxq020/miniconda3/envs/ksrates_2/lib/python3.8/site-packages
Requires:
Required-by: biopython, bokeh, fastcluster, KDEpy, matplotlib, numexpr, pandas, scikit-learn, scikit-learn-extra, scipy, seaborn

This means that my numpy version is 1.21.2.

Thank you for your reply. I will initiate a new one for the next question.

**Comment by Cecilia-Sensalari** [comment]
Thanks for checking numpy out :) The version is okay.

Your Traceback log also says, at the end, that numpy was called when ksrates imported fastcluster:
```
File "/usr/local/lib/python3.8/dist-packages/wgd_ksrates/phy.py", line 35, in <module>
    import fastcluster
File "/media/desk15/sxq020/.local/lib/python3.8/site-packages/fastcluster.py", line 37, in <module>
    from _fastcluster import linkage_wrap, linkage_vector_wrap
```
Can you check if the fastcluster version is set according to requirements (`fastcluster==1.1.25`)?

Best,
Cecilia

**Comment by majssssa** [comment]
Thanks for the tip, I checked the fastcluster version and it was indeed 1.1.25. However, I just turned on my other computer, re-followed the instructions to install ksrates, and then tested it, this time without any errors, and it worked. Looks like there's something wrong with my computer.

**Comment by Cecilia-Sensalari** [comment]
I see!
Perhaps comparing the software installed in the two computers can help identifying what is giving the error message. E.g. different Python version, miniconda... Should you find something out, keep me posted :)

Cheers,
Cecilia
