### ISSUE TITLE
No output files

### ISSUE THREAD

**Issue by abcbot123** [VIB-PSB/ksrates#56]
Hi,
I'm using the ksrates docker image. I have an issue with not getting relevant output files. Here are the codes I have run,
```
/usr/local/bin/ksrates init config_oxalis.txt
/usr/local/bin/ksrates paralogs-ks config_oxalis.txt --n-threads 16
/usr/local/bin/ksrates orthologs-ks config_oxalis.txt oxalis populus --n-threads 16
/usr/local/bin/ksrates orthologs-ks config_oxalis.txt oxalis arabidopsis --n-threads 16
/usr/local/bin/ksrates orthologs-ks config_oxalis.txt oxalis vitis --n-threads 16
/usr/local/bin/ksrates orthologs-analysis config_oxalis.txt
/usr/local/bin/ksrates plot-orthologs config_oxalis.txt
/usr/local/bin/ksrates orthologs-adjustment config_oxalis.txt
/usr/local/bin/ksrates plot-paralogs config_oxalis.txt
/usr/local/bin/ksrates plot-tree config_oxalis.txt
/usr/local/bin/ksrates paralogs-analyses config_oxalis.txt
```

When I check the errors, this is what I found this error related to i-adhore step,
```
INFO	Done
INFO	---
INFO	Running wgd colinearity Ks pipeline...
INFO	No colinearity anchor pair Ks data, will run wgd colinearity Ks analysis
INFO	Checking external software...
INFO	This is i-ADHoRe v3.0.
INFO	Creating i-ADHoRe tmp directory /var/lib/condor/execute/slot1/dir_774720/paralog_distributions/wgd_oxalis/oxalis.ks_anchors_tmp
INFO	Parsing GFF file
INFO	Writing gene lists for i-ADHoRe
INFO	Writing families file for i-ADHoRe
INFO	Writing i-ADHoRe configuration file
INFO	Running i-ADHoRe 3.0...
INFO	i-adhore /var/lib/condor/execute/slot1/dir_774720/paralog_distributions/wgd_oxalis/oxalis.ks_anchors_tmp/i-adhore.conf
ERROR	i-ADHoRe execution failed with return code: -6
ERROR	i-ADHoRe standard error output:
i-adhore: /i-adhore/src/Profile.cpp:95: void Profile::createNodes(const std::set<Link>&, const std::vector<GeneList*>&, std::vector<std::vector<Node*> >&, bool, bool) const: Assertion `geneX.isPairWith(geneY)' failed.
ERROR	Exiting.
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
```

Here are the other errors and warnings I got,
```
INFO	Finished 1242/1243 gene family analyses...
INFO	Finished 1243/1243 gene family analyses...
INFO	Finished all gene family analyses
INFO	Analysis done
INFO	Making results data frame
INFO	Removing tmp directory
INFO	---
INFO	Done
INFO	Fri Mar  8 16:10:48 2024
INFO	Done
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Computing ortholog distribution peaks with related error
INFO	Fri Mar  8 16:10:48 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
WARNING	Ortholog peak database [ortholog_peak_db.tsv] not found or empty: a new one is now generated.
WARNING	Ortholog Ks list database [ortholog_ks_list_db.tsv] not found or empty: a new one is now generated.
INFO	
INFO	Oxalis oulophora and Populus trichocarpa:
INFO	- Extracting ortholog Ks list
INFO	- Computing distribution peak through bootstrap (200 iterations)
INFO	- Adding peak to ortholog peak database
INFO	- Adding Ks list to ortholog Ks list database
INFO	
INFO	Oxalis oulophora and Vitis vinifera:
INFO	- Extracting ortholog Ks list
INFO	- Computing distribution peak through bootstrap (200 iterations)
INFO	- Adding peak to ortholog peak database
INFO	- Adding Ks list to ortholog Ks list database
INFO	
INFO	Populus trichocarpa and Vitis vinifera:
INFO	- Extracting ortholog Ks list
WARNING	  Ortholog Ks TSV file not found [populus_vitis.ks.tsv]. Skipping peak estimate.
INFO	
INFO	Arabidopsis thaliana and Oxalis oulophora:
INFO	- Extracting ortholog Ks list
INFO	- Computing distribution peak through bootstrap (200 iterations)
INFO	- Adding peak to ortholog peak database
INFO	- Adding Ks list to ortholog Ks list database
INFO	
INFO	Arabidopsis thaliana and Populus trichocarpa:
INFO	- Extracting ortholog Ks list
WARNING	  Ortholog Ks TSV file not found [arabidopsis_populus.ks.tsv]. Skipping peak estimate.
INFO	
INFO	Arabidopsis thaliana and Vitis vinifera:
INFO	- Extracting ortholog Ks list
WARNING	  Ortholog Ks TSV file not found [arabidopsis_vitis.ks.tsv]. Skipping peak estimate.
INFO	
WARNING	Number of failed peak computations: 3
WARNING	
INFO	All done
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Plotting ortholog distributions for all ortholog trios
INFO	Fri Mar  8 16:10:51 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
INFO	
INFO	Plotting ortholog Ks distributions for species pair [Oxalis oulophora - Populus trichocarpa]
WARNING	- Skipping all outspecies: not enough ortholog data available (PDF figure not generated)
INFO	
INFO	Plotting ortholog Ks distributions for species pair [Oxalis oulophora - Vitis vinifera]
WARNING	- Skipping all outspecies: not enough ortholog data available (PDF figure not generated)
WARNING	
WARNING	The species pairs listed below are not (yet) available in the ortholog databases
WARNING	The trios involving such species pairs have not been plotted
WARNING	
WARNING	Species pairs not yet available in both Ks peak and Ks list ortholog databases:
WARNING	  Arabidopsis thaliana - Populus trichocarpa
WARNING	  Arabidopsis thaliana - Vitis vinifera
WARNING	  Populus trichocarpa - Vitis vinifera
WARNING	
WARNING	Please compute their ortholog Ks data and/or add the ortholog data to the databases,
WARNING	then rerun this step.
INFO	
INFO	All done
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - 
INFO	Rate-adjustment of ortholog Ks distributions
INFO	Fri Mar  8 16:10:52 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
INFO	
INFO	Performing rate-adjustment of each divergent pair by using one or more outgroups:
INFO	 - Adjusting the peak for [Oxalis oulophora] and [Populus trichocarpa] with outspecies [Vitis vinifera]
WARNING	Couldn't process trio [Oxalis oulophora, Populus trichocarpa, Vitis vinifera]:
WARNING	 - [Populus trichocarpa_Vitis vinifera] not in ortholog peak database.
INFO	 - Adjusting the peak for [Oxalis oulophora] and [Populus trichocarpa] with outspecies [Arabidopsis thaliana]
WARNING	Couldn't process trio [Oxalis oulophora, Populus trichocarpa, Arabidopsis thaliana]:
WARNING	 - [Arabidopsis thaliana_Populus trichocarpa] not in ortholog peak database.
INFO	 - Adjusting the peak for [Oxalis oulophora] and [Vitis vinifera] with outspecies [Arabidopsis thaliana]
WARNING	Couldn't process trio [Oxalis oulophora, Vitis vinifera, Arabidopsis thaliana]:
WARNING	 - [Arabidopsis thaliana_Vitis vinifera] not in ortholog peak database.
INFO	Rate-adjustment results for each trio saved in TSV format [adjustment_table_oxalis_all.tsv]
INFO	
INFO	Rate-adjustment results as consensus values saved in TSV format [adjustment_table_oxalis.tsv]
INFO	
INFO	All done
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Generating mixed paralog and ortholog distributions
INFO	Fri Mar  8 16:10:53 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
ERROR	Anchor pair Ks TSV file not found at default position [paralog_distributions/wgd_oxalis/oxalis.ks_anchors.tsv].
ERROR	Exiting
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Generating PDF of input tree with branch length equal to Ks distances
INFO	Fri Mar  8 16:10:54 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
WARNING	Rate-adjustment data not available yet: PDF figure of phylogenetic tree not generated.
INFO	Exiting
```

```
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Clustering anchorpoints Ks values to reconstruct recent WGD events
INFO	Fri Mar  8 16:10:55 2024
INFO	- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
INFO	Loading parameters and input files
INFO	 - maximum EM iterations: 600
INFO	 - number of EM initializations: 10
ERROR	anchorpoints.txt file not found at default position [paralog_distributions/wgd_oxalis/oxalis_i-adhore/anchorpoints.txt].
ERROR	multiplicons.txt file not found at default position [paralog_distributions/wgd_oxalis/oxalis_i-adhore/anchorpoints.txt].
ERROR	segments.txt file not found at default position [paralog_distributions/wgd_oxalis/oxalis_i-adhore/segments.txt].
ERROR	multiplicon_pairs.txt file not found at default position [paralog_distributions/wgd_oxalis/oxalis_i-adhore/multiplicon_pairs.txt].
ERROR	list_elements.txt file not found at default position [paralog_distributions/wgd_oxalis/oxalis_i-adhore/list_elements.txt].
ERROR	oxalis.ks_anchors.tsv file not found at default position [paralog_distributions/wgd_oxalis/oxalis.ks_anchors.tsv].
ERROR	Exiting
```

Do you have any suggestions to fix this error?
Thanks so much!

**Comment by Cecilia-Sensalari** [comment]
Hi abcbot123 :)

Thanks for reaching out. At a first glance, the problem originates within i-ADHoRe, while the other warnings in the later commands arise from the fact that some orthologs Ks data are still not generated (probably interrupted by the error?).

The i-ADHoRe error message says:
```
ERROR i-ADHoRe execution failed with return code: -6
ERROR i-ADHoRe standard error output:
i-adhore: /i-adhore/src/Profile.cpp:95: void Profile::createNodes(const std::set&, 
const std::vector<GeneList*>&, std::vector<std::vector<Node*> >&, bool, bool) 
const: Assertion `geneX.isPairWith(geneY)' failed.
```

It's thus related to line 95 in file [Profile.cpp](https://github.com/VIB-PSB/i-ADHoRe/blob/f7c2d4b2ec282c2e11e13ff9e83a166f2fbdcd66/src/Profile.cpp#L95).
I never encountered such error and right now I don't know what can be causing it.

It seems to me that i-ADHoRe is not finding the data it expects to find. Could you double check if your GFF file follows the standard format and could you make sure you're parsing it with the [correct](https://ksrates.readthedocs.io/en/latest/configuration.html#ksrates-configuration-file) gff_feature and gff_attribute?
If you have successfully run other species in the past, can you think about something different in the input files?

Cheers,
Cecilia

**Comment by Cecilia-Sensalari** [comment]
Here's an update :)
I noticed that your error message is the same reported in a recent [issue](https://github.com/VIB-PSB/i-ADHoRe/issues/12) on i-ADHoRe itself.
When building the ksrates docker container, we are actually basing it on the vib/i-adhore GitHub repo (see first line in our [dockerfile](https://github.com/VIB-PSB/ksrates/blob/master/Dockerfile)). This makes me think that your issue is inherited from i-ADHoRe. I'll get in touch with its maintainers to look into that!

If the above is correct, then you should still be able to run ksrates using the whole-paranome pipeline, deactivating the colinearity pipeline (see [configuration](https://ksrates.readthedocs.io/en/latest/configuration.html#ksrates-configuration-file)).

Best,
Cecilia

**Comment by Cecilia-Sensalari** [comment]
Hi :) It would also probably still be helpful if you could provide us with your input FASTA and GFF files for Oxalis, as well as with the parsing gff_features and gff_attribute you have chosen. Thanks!

**Comment by abcbot123** [comment]
Hi Cecilia,
Thanks so much for your response. I have recheck my gff3 file and there was an issue with the format. I have fixed it and got the output files. But I'm struggling with how to explain my results. Could you please help me to figure out how to explain my output files? If so, I can send those .pdf files I got.
Thanks so much!

**Comment by abcbot123** [comment]
Hi Cecilia,
Thanks so much for your response. I have recheck my gff3 file and there was
an issue with the format. I have fixed it and got the output files. But I'm
struggling with how to explain my results. Could you please help me to
figure out how to explain my output files? If so, I can send those .pdf
files I got.
Thanks so much!

**Comment by Cecilia-Sensalari** [comment]
Hi, I'm happy it was just a format issue! Feel free to share what it was if you think other people might encounter the same problem.
Sure, we can have a look together at your output files. What about using [gitter](https://gitter.im/) to communicate? You can sign in with your GitHub account, then we can share files and text.
Cheers,
Cecilia

**Comment by abcbot123** [comment]
Hi Cecilia,
Yes, I can do that. I have login to gitter using my GitHub account but I couldn't find you to sent a message.

**Comment by wjq1981** [comment]
Hi, I'm having a similar problem, here's the code to run and the errors reported, can you help me see how to fix it?

ksrates plot-paralogs config_Bchinensis.txt

INFO Generating mixed paralog and ortholog distributions
INFO Sun Jul 21 15:14:52 2024
INFO Loading parameters and input files
ERROR Anchor pair Ks TSV file not found at default position [paralog_distributions/wgd_Bchinensis/Bchinensis.ks_anchors.tsv].
ERROR Exiting
 
#
There is also an error in the above step

ksrates orthologs-analysis config_Bchinensis.txt

INFO Computing ortholog distribution peaks with related error
INFO Sun Jul 21 15:31:43 2024

INFO Loading parameters and input files
INFO
INFO Belamcanda chinensis and Crocus sativus: data already present in ortholog database
INFO
INFO Asparagus officinal and Belamcanda chinensis: data already present in ortholog database
INFO
INFO Asparagus officinal and Crocus sativus: data already present in ortholog database
INFO
INFO All done

**Comment by Cecilia-Sensalari** [comment]
Hi wjq1981,

Thanks for reaching out!

The error originating from command `plot-paralogs` says that, while trying to plot the anchor pair Ks distribution, it doesn't find the file listing all the anchor pair Ks values; it also says that this file is normally located at `paralog_distributions/wgd_Bchinensis/Bchinensis.ks_anchors.tsv`.
Have you already generated such file? To do so, you have to run command `paralogs-ks` also for the anchor pairs by setting `collinearity = yes` in configuration file `config_Bchinensis.txt`.
If you did already generate it, have you perhaps moved it or renamed it? In that case, it doesn't find it.
Or, perhaps you're lunching the command line from a wrong location, from which it can't find the file according to the default path.

The output from command `orthologs-analysis` doesn't have any error message :) The INFO lines say that the ortholog Ks distributions for all species pairs have been already generated and are already available in the ortholog database, so they are not calculated again.

Let me know how it goes, and if this doesn't help we can investigate further!
Cheers,
Cecilia

**Comment by wjq1981** [comment]
Thank you for your prompt reply.
'collinearity = yes' is so in the “config_Bchinensis.txt” file.
At the same time I didn't find the file “Bchinensis.ks_anchors.tsv” in any of the generated directories.
And to rule out the possibility that it's just me, I ran “config_elaeis.txt” from test and got the same error!

###
 ksrates plot-paralogs config_elaeis.txt
INFO    - - - - - - - - - - - - - - - - - - - - - - - - - -
INFO    Generating mixed paralog and ortholog distributions
INFO    Mon Jul 22 16:21:45 2024
INFO    - - - - - - - - - - - - - - - - - - - - - - - - - -
INFO    Loading parameters and input files
ERROR   Anchor pair Ks TSV file not found at default position [paralog_distributions/wgd_elaeis/elaeis.ks_anchors.tsv].
ERROR   Exiting

**Comment by wjq1981** [comment]
This is a list of all the files in the “paralog_distributions” directory.

paralog_distributions/wgd_elaeis
├── elaeis.blast.tsv
├── elaeis.ks_anchors_tmp
│   ├── families.tsv
│   ├── i-adhore.conf
│   ├── i-adhore_gene_lists
│   │   ├── EG5.1_Chr10.lst
│   │   ├── EG5.1_Chr11.lst
│   │   ├── EG5.1_Chr12.lst
│   │   ├── EG5.1_Chr13.lst
│   │   ├── EG5.1_Chr14.lst
│   │   ├── EG5.1_Chr15.lst
│   │   ├── EG5.1_Chr16.lst
│   │   ├── EG5.1_Chr1.lst
│   │   ├── EG5.1_Chr2.lst
│   │   ├── EG5.1_Chr3.lst
│   │   ├── EG5.1_Chr4.lst
│   │   ├── EG5.1_Chr5.lst
│   │   ├── EG5.1_Chr6.lst
│   │   ├── EG5.1_Chr7.lst
│   │   ├── EG5.1_Chr8.lst
│   │   ├── EG5.1_Chr9.lst
│   │   ├── p5_sc00010.lst
│   │   ├── ..............
│   │   └── p5_sc40286.lst
│   └── i-adhore_out
│       ├── AlignmentMultiplicon1.svg
│       ├── AlignmentMultiplicon2.svg
│       ├── AlignmentMultiplicon3.svg
│       ├── AlignmentMultiplicon4.svg
│       ├── AlignmentMultiplicon5.svg
│       ├── alignment.txt
│       ├── anchorpoints.txt
│       ├── baseclusters.txt
│       ├── genes.txt
│       ├── list_elements.txt
│       ├── multiplicon_pairs.txt
│       ├── multiplicons.txt
│       └── segments.txt
├── elaeis.ks.tsv
└── elaeis.mcl.tsv

Wouldn't 'elaeis.ks.tsv' be 'elaeis.ks_anchors.tsv' here either? Because it's the first time I've run it and I don't know what their contents should be!

**Comment by Cecilia-Sensalari** [comment]
Alright! In the docs you can find the description of the output files: for example [here](https://ksrates.readthedocs.io/en/latest/input_output.html#ks-estimate-output-wgd) it explains that `elaeis.ks.tsv` and `elaeis.ks_anchors.tsv` are similar in content, but the first is the list of Ks values for all paralogs (paranome), while the second is restricted to only anchor pairs.

The directory structure can tell us something: normally `elaeis.ks_anchors_tmp` is a temporary directory that is deleted once the final `elaeis.ks_anchors.tsv` is obtained. Therefore, I think that command `paralogs-ks` encountered an error during its execution while computing anchor pairs; could you check its output log?

**Comment by wjq1981** [comment]
This is the output log.
#
ksrates paralogs-ks config_elaeis.txt --n-threads=64

INFO    - - - - - - - - - - - - - - - - - - - - -
INFO    Paralog wgd analysis for species [elaeis]
INFO    Mon Jul 22 16:57:41 2024
INFO    - - - - - - - - - - - - - - - - - - - - -
INFO    Checking if sequence data files exist and if sequence IDs are compatible with wgd pipeline...
INFO    Completed
INFO    Creating directory [paralog_distributions/]
INFO    Running wgd paralog Ks pipeline...
INFO    ---
INFO    Checking external software...
INFO    makeblastdb: 2.5.0+
INFO    blastp: 2.5.0+
INFO    mcl 14-137
INFO    MUSCLE v3.8.1551 by Robert C. Edgar
INFO    AAML in paml version 4.10.7, June 2023
INFO    Usage for FastTree version 2.1.8 Double precision (No SSE3):
INFO    Creating output directory /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis
INFO    Translating CDS file elaeis.fasta...
INFO    ---
INFO    Running all versus all Blastp
INFO    Writing protein Blastdb sequences to /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/...
INFO    Writing protein query sequences to /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/...
INFO    Performing all versus all Blastp (this might take a while)...
INFO    Making Blastdb
INFO    makeblastdb -in /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/elaeis.db.fasta -dbtype prot
INFO    makeblastdb output:
Building a new DB, current time: 07/22/2024 16:57:42
New DB name:   /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/elaeis.db.fasta
New DB title:  /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/elaeis.db.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 500 sequences in 0.108267 seconds.
INFO    Running Blastp
INFO    blastp -db /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/elaeis.db.fasta -query /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast_tmp/elaeis.query.fasta -evalue 1e-10 -outfmt 6 -num_threads 64 -out /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.blast.tsv
INFO    All versus all Blastp done
INFO    Removing tmp directory
INFO    ---
INFO    Running gene family construction (MCL clustering with inflation factor = 2.0)
INFO    Started MCL clustering (mcl)
INFO    ---
INFO    Running whole paranome Ks analysis...
INFO    Started analysis of 66 gene families in parallel using 64 threads
INFO    Performing analysis on gene family GF_000001 (size 13)
INFO    Performing analysis on gene family GF_XXXXXX (size 2)
INFO    Performing analysis on gene family GF_000066 (size 2)
INFO    Finished 2/66 gene family analyses...
INFO    Finished 47/66 gene family analyses...
INFO    Finished 63/66 gene family analyses...
INFO    Finished 64/66 gene family analyses...
INFO    Finished 65/66 gene family analyses...
INFO    Finished 66/66 gene family analyses...
INFO    Finished all gene family analyses
INFO    Analysis done
INFO    Making results data frame
INFO    Computing weights, outlier cut-off at Ks > 20
INFO    Removing tmp directory
INFO    ---
INFO    Done
INFO    ---
INFO    Running wgd colinearity Ks pipeline...
INFO    No colinearity anchor pair Ks data, will run wgd colinearity Ks analysis
INFO    Checking external software...
INFO    This is i-ADHoRe v3.0.
INFO    Creating i-ADHoRe tmp directory /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.ks_anchors_tmp
INFO    Parsing GFF file
INFO    Writing gene lists for i-ADHoRe
INFO    Writing families file for i-ADHoRe
INFO    Writing i-ADHoRe configuration file
INFO    Running i-ADHoRe 3.0...
INFO    i-adhore /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.ks_anchors_tmp/i-adhore.conf
INFO    i-ADHoRe output:
This is i-ADHoRe v3.0.
Copyright (c) 2002-2010, Flanders Interuniversity Institute for Biotechnology, VIB.
Algorithm designed by Klaas Vandepoele, Cedric Simillion, Jan Fostier, Dieter De Witte,
Koen Janssens, Sebastian Proost, Yvan Saeys and Yves Van de Peer.

Process 1/1 is alive on suma-Nd.


************* i-ADHoRe parameters *************
        Number of genelists = 2643
        Blast table = /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.ks_anchors_tmp/families.tsv
        Output path = /dev/hdd/soft/ksrates/test/paralog_distributions/wgd_elaeis/elaeis.ks_anchors_tmp/i-adhore_out/
        Gap size = 30
        Cluster gap size = 35
        Cloud gap size = 0
        Cloud cluster gap size = 0
        Max gaps in alignment = 35
        Tandem gap = 15
        Flush output = 1000
        Q-value = 0.75
        Anchorpoints = 3
        Probability cutoff = 0.01
        Cloud filtering method = Binomial
        Level 2 only = false
        Use family = true
        Write statistics = false
        Alignment method = GreedyGraphbased4
        Multiple hypothesis correction = FDR
        Number of threads = 64
        Compare aligners = false
        Collinear searches only
        Visualize GHM.png = false
        Visualize Alignment = true
        Verbose output = true
************ END i-AdDHoRe parameters *********

Creating dataset...                     done. (time: 0.132908s)
Mapping gene families...                done. (time: 0.0924711s)
Remapping tandem duplicates...  done. (time: 0.043623s)
Writing genelists file...               done. (time: 0.480689s)
Collinear Search
Level 2 multiplicon detection...        done. (time: 1.85592s)
Profile detection...
5 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
4 multiplicons to evaluate - evaluating level 2 multiplicon... 0 new multiplicons found.
3 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
2 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
1 multiplicons to evaluate - evaluating level 2 multiplicon... level-2 multiplicon is redundant
Flushing output files...Visualize AlignedProfiles
done.
Time for Higher Level Detection: 0.075561s.


All Done!  Bye...
ERROR   i-ADHoRe execution failed with standard error output:
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
ERROR   Exiting.

**Comment by Cecilia-Sensalari** [comment]
Based on the output log, i-ADHoRe was doing alright until the very end: it printed "All Done! Bye..." and then something generated an error with message "Authorization required, but no authorization protocol specified".
I've never encountered this error and I don't know what it refers to. After a quick search online and a question to ChatGPT, I see that it is related to "Unix-like system using the X Window System (X11)", so to your environment where you are running ksrates/i-ADHoRe. I suggest you search this error and see whether some other users already had similar problems, or that you ask ChatGPT and/or your IT group for help. I'll have a look myself as well in the meantime, because I don't fully grasp the topic...

For example, here the problem was that the user was running commands as "root" and not as "user": https://www.reddit.com/r/linux4noobs/comments/lu1plx/hi_i_get_this_authorization_required_but_no/ and https://stackoverflow.com/questions/48833451/no-protocol-specified-when-running-a-sudo-su-app-on-ubuntu-linux

**Comment by wjq1981** [comment]
Thank you very much for your answer. 
Another problem I have is that I'm getting errors running with docker, I uninstalled and reinstalled it and still get the same error, can you see if it's a software problem or a docker problem? I'm using other docker software and it's working.

docker run --rm -v $PWD:/temp -w /temp vibpsb/ksrates -h
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-h": executable file not found in $PATH: unknown.

**Comment by Cecilia-Sensalari** [comment]
Let's see, [here](https://ksrates.readthedocs.io/en/latest/usage.html#run-example-case-as-a-manual-pipeline) in the docs I showed how to use the docker commands, and it looks like you chose the one to "launch a single command through the container":
<img width="662" alt="image" src="https://github.com/user-attachments/assets/d2051966-8c8d-408e-884d-8667de68a03a">
In order to run such command, for example `-h`, you need to type`ksrates -h` (and not only `-h`) at the end of the docker command line (compare with the command line in your previous message). Can you try again with the following edit?
``
docker run --rm -v $PWD:/temp -w /temp vibpsb/ksrates ksrates -h
``
Hope this helps!

**Comment by wjq1981** [comment]
Yeah, you're right. Now that it's working with “ksrates”, I'm crying at my own stupidity. Good day！

**Comment by Cecilia-Sensalari** [comment]
No worries, great to hear this worked! Should you find an answer for the authorization-related error, let me know :)
